services:

  db:

    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer:latest
    restart: always
    ports:
    - 8888:8080